config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :documents

  authenticated :user do
    root "documents#index", as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :find_doc, only: [:show, :update, :destroy, :edit]

  def index
    @docs = Document.where(user_id: current_user).order("created_at DESC")
  end

  def show
  end

  def new
    @doc = current_user.documents.build
  end

  def create
    @doc = current_user.documents.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to documents_path
  end

  private

  def find_doc
    @doc = Document.find(params[:id])
  end

  def doc_params
    params.require(:document).permit(:title, :content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.erb
<%= form_for @doc do |f| %>

  <div class="form-group">
    <h3><%= f.label :title %></h3>
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %><br>
  </div>

  <div class="form-group">
    <h3><%= f.label :content %></h3>
    <%= f.text_area :content, placeholder: "So what's on your mind?", class: "form-control", rows: "5" %><br>
  </div>

  <%= f.submit "Save", class: "btn btn-info" %>

<% end %>

app/views/documents/edit.html.erb
<div class="col-xs-8 col-xs-offset-2">

<h1>Edit <%= @doc.title %></h1>

<%= render 'form' %>

<%= link_to "Back", document_path(@doc) %>

</div>

app/views/documents/index.html.erb
<div class="col-xs-6 col-xs-offset-3">

  <% unless @docs.blank? %>

  <% @docs.each do |doc| %>

  <%= link_to doc do %> <!-- This will link to entire div -->
  <div id='document-box'>
    <div class="container-fluid">
      <div id='document-title'>
        <h2><%= doc.title %></h2>
      </div>

      <div id='time-ago'>
        <h5><%= time_ago_in_words(doc.created_at) %></h5>
      </div>

      <div id='document-content'>
        <p><%= truncate(doc.content, length: 50 ) %></p>
      </div>

      <div class="btn-group pull-right" role="group">
        <%= link_to 'Edit', edit_document_path(doc), class: 'btn btn-info' %>
        <%= link_to 'Delete', document_path(doc), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>

  <% else %>

  <h2><%= link_to "Create Doc!", new_document_path, class: 'btn btn-primary btn-lg' %></h2>

  <% end %>

</div>

app/views/documents/new.html.erb
<div class="col-xs-8 col-xs-offset-2">

<h1>New Document</h1>

<%= render 'form' %>

</div>

app/views/documents/show.html.erb
<div class='col-xs-8 col-xs-offset-2 'id="show-box">

  <div id='show-title'>
    <h1><%= @doc.title %></h1>
  </div>

  <div id='show-content'>
    <%= simple_format(@doc.content) %>
  </div>

  <div class="btn-group" role="group" id='show-button'>
    <%= link_to "Edit Document", edit_document_path(@doc), class: 'btn btn-info' %>
    <%= link_to "Delete", document_path(@doc), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-primary' %>
  </div>

</div>

app/views/layouts/_main.html.erb
<div class="container-fluid" id="main-box">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</div>

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "FileCab", root_path, class: "navbar-brand" %>
    </div>

    <!-- Navbar left -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li></li>
        <li></li>
      </ul>

      <!-- Navbar right -->
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_document_path do %>
          <i class="glyphicon glyphicon-file"> Create-Doc</i>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
          <i class="glyphicon glyphicon-user"> Edit-Profile</i>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you ready to leave?"} do %>
          <i class="glyphicon glyphicon-log-out"> Log-Out</i>
          <% end %>
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filecabinet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/nav' %>
  <%= render 'layouts/main' %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron" id="welcome-page">
  <div class="container">
    <div class="col-xs-8 col-xs-offset-2" id="welcome-box">
      <h1>Welcome to FileCabinet!</h1>
      <h3>Take your digital filing to a new level!</h3>
      <p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger btn-lg" %></p>
      <p>Already a member? <%= link_to "Log In", new_user_session_path %></p>
    </div>
  </div>
</div>